volumes:
  data:
    driver: local
  ollama_data:
    driver: local

services:

  ollama:
    build:
      dockerfile: Dockerfile
      context: ./ollama/
    container_name: ollama
    volumes:
      - ./ollama/ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  postgres-database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql
    
  api:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./api/
    command: >
      bash -c "uv run fastapi dev main.py --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres-database
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST=postgres-database
    env_file:
      - .env
    volumes:
      - ./api:/app
    restart: on-failure
  
  ui:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./ui/
    ports:
      - 3000:3000
    environment:
      - STAGE=local
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    restart: on-failure
